#!/bin/bash

#targetdir=$HOME
targetdir=/home/mike/.test

for f in $(find . -type f -not -path "./.git*" -not -name "*README.md" -not -name link); do
	strippedfile="${f:2}"
	targetfile="$targetdir/$strippedfile"
	if [ -e "$targetfile" ] && [ ! -h "$targetfile" ]; then
		mv "$targetfile" "${targetfile}.old"
	elif [ ! -e "$targetfile" ]; then
		mkdir -p "$(dirname ${targetfile})"
	fi
	ln -s "$(pwd)/$strippedfile" "$targetfile"
done
