#!/bin/sh

# Reload this configuration on the fly
super + Escape
    pkill -USR1 -x sxhkd

# Quit X
super + alt + Escape
    bspc quit

# Move window control, window
super + {_,shift + }{h,j,k,l}
    bspc window -{f,s} {left,down,up,right}

# Set split direction for active window
super + ctrl + {h,j,k,l}
    bspc window -p {left,down,up,right}

# Grow / shrink active window
super + alt + {h,j,k,l}
    bspc window -e {left -10,down +10,up -10,right +10}

super + alt + shift + {h,j,k,l}
    bspc window -e {right -10,up +10,down -10,left +10}

# Toggle active window floating, fullscreen
super + {s,d}
    bspc window -t {floating,fullscreen}

# Close/kill window
super + {_,shift + }x
    bspc window -{c,k}

# Move to workspace, move active window to workspace
super + {_,shift + }{1-9,0}
    bspc {desktop -f,window -d} ^{1-9,10}

super + {_,shift + }{u,i}
    bspc {desktop -f,window -d} {prev,next}

# ?????
super + a
    bspc desktop -l next

# ?????
super + z
    bspc desktop -B

# Go to previously visited window (from current workspace), workspace
super + {grave,Tab}
    bspc {window,desktop} -f last

# Go to previously visited window from any workspace
super + apostrophe
    bspc window -s last

# ?????
super + {o,p}
    bspc control --record-history off; \
    bspc window {older,newer} -f; \
    bspc control --record-history on

# ?????
super + y
    bspc window -w last.manual

# ?????
super + g
    bspc window -s biggest

# Cycle through windows
super + {n,b}
    bspc window -f {next,prev}

# ?????
super + {comma,period}
    bspc desktop -C {backward,forward}

# Reset split direction for active window, ?????
super + ctrl + {_,shift + }space
    bspc {window -p cancel,desktop -c}

# Set split ratio for active window
super + ctrl + {1-9}
    bspc window -r 0.{1-9}

# Change focus with mouse
~button1
    bspc pointer -g focus

# Move, resize with mouse
super + button{1-3}
    bspc pointer -g {move,resize_side,resize_corner}

# ?????
super + !button{1-3}
    bspc pointer -t %i %i

# ?????
super + @button{1-3}
    bspc pointer -u

# Volume keys
@F{11,12}
    amixer set Master 5%{-,+} unmute

super + alt + space
    amixer set Master toggle

# Multimedia keys
super + alt + {u,i,o}
    mpc {prev,toggle,next}

# Screenshot
{_,alt + }@Print
    scrot {_,-s}

# Suspend / screen lock
super + {_,shift + }@F1
    {suspend,lock}

# Applications
super + Return
    $LAUNCH_TERMINAL

super + f
    $LAUNCH_FILE_MANAGER

super + w
    $LAUNCH_BROWSER

super + shift + w
    google-chrome-stable --new-window

super + e
    $LAUNCH_EDITOR
	
super + a
    $LAUNCH_MPLAYER

super + space
    $LAUNCHER
#    j4-dmenu-desktop --term=urxvtc --dmenu="dmenu -i -fn 'Meslo LG S-10'"
