#!/bin/sh

# Reload this configuration on the fly
super + ctrl + r
    pkill -USR1 -x sxhkd

# Quit X
super + ctrl + q
    killall panel && bspc quit

# Move window control, window; set split direction
super + {_,ctrl + ,shift + }{h,j,k,l}
    bspc window -{f,s,p} {left,down,up,right}

# Grow / shrink active window
super + alt + {h,j,k,l}
    bspc window -e {left -10,down +10,up -10,right +10}

super + alt + shift + {h,j,k,l}
    bspc window -e {right -10,up +10,down -10,left +10}

# Toggle active window floating, fullscreen
super + {s,d}
    bspc window -t {floating,fullscreen}

# Close/kill window
super + {ctrl +,shift +} x
    bspc window -{c,k}

# Go to workspace, move active window to workspace
super + {_,ctrl + }{1-9,0}
    bspc {desktop -f,window -d} ^{1-9,10}

super + {_,ctrl + }{u,i}
    bspc {desktop -f,window -d} {prev,next}

# ?????
super + c
    bspc desktop -l next

# ?????
super + z
    bspc desktop -B

# Go to previously visited window (from current workspace), workspace
super + {grave,Tab}
    bspc {window,desktop} -f last

# Go to previously visited window from any workspace
super + apostrophe
    bspc window -s last

# ?????
super + {_,ctrl + }o
    bspc control --record-history off; \
    bspc window {older,newer} -f; \
    bspc control --record-history on

# ?????
super + y
    bspc window -w last.manual

# ?????
super + g
    bspc window -s biggest

# Cycle through windows
super + ctrl + {n,p}
    bspc window -f {next,prev}

# ?????
super + {comma,period}
    bspc desktop -C {backward,forward}

# Reset split direction for active window, ?????
super + {shift +,ctrl +} space
    bspc {window -p cancel,desktop -c}

# Set split ratio for active window
super + shift + {1-9}
    bspc window -r 0.{1-9}

# Change focus with mouse
~button1
    bspc pointer -g focus

# Move, resize with mouse
super + button{1-3}
    bspc pointer -g {move,resize_side,resize_corner}

# ?????
super + !button{1-3}
    bspc pointer -t %i %i

# ?????
super + @button{1-3}
    bspc pointer -u

# Volume keys
@F{11,12}
    volume {down,up} 5

super + alt + space
    volume mute

# Multimedia keys
super + {p,a,n}
    mpc {prev,toggle,next}

# Brightness keys
@F{9,10}
    brightness {down,up} 10

# Screenshot
{_,ctrl + }@Print
    scrot{_, -s}

# Screen lock (suspend with suspend key)
super + @F1
    locky ~/Pictures/gimp/the_way_is_shut.png

# Applications
super + Return
    $TERMINAL

super + ctrl + Return
    $LAUNCH_BROWSER

super + shift + Return
    $LAUNCH_ALT_BROWSER

super + space
    $LAUNCHER
