#!/bin/sh



#--------------------------------------
# bspwm
#--------------------------------------

# Quit X
super + alt + Escape
    bspc quit

# Close window
super + shift + q
    bspc window -c

# ?????
super + a
    bspc desktop -l next

# ?????
super + z
    bspc desktop -B

# Toggle active window floating, fullscreen
super + {s,d}
    bspc window -t {floating,fullscreen}

# Go to previously visited window (from current workspace), workspace
super + {grave,Tab}
    bspc {window,desktop} -f last

# Go to previously visited window from any workspace
super + apostrophe
    bspc window -s last

# ?????
super + {o,p}
    bspc control --record-history off; \
    bspc window {older,newer} -f; \
    bspc control --record-history on

# ?????
super + y
    bspc window -w last.manual

# ?????
super + g
    bspc window -s biggest

# Move window control, window
super + {_,shift + }{h,j,k,l}
    bspc window -{f,s} {left,down,up,right}

# Cycle through windows
super + {n,b}
    bspc window -f {next,prev}

# ?????
super + {comma,period}
    bspc desktop -C {backward,forward}

# Set split direction for active window
super + ctrl + {h,j,k,l}
    bspc window -p {left,down,up,right}

# Reset split direction for active window, ?????
super + ctrl + {_,shift + }space
    bspc {window -p cancel,desktop -c}

# Grow / shrink active window
super + alt + {h,j,k,l}
    bspc window -e {left -10,down +10,up -10,right +10}

super + alt + shift + {h,j,k,l}
    bspc window -e {right -10,up +10,down -10,left +10}

# Set split ratio for active window
super + ctrl + {1-9}
    bspc window -r 0.{1-9}

# Move to workspace, move active window to workspace
super + {_,shift + }{1-9,0}
    bspc {desktop -f,window -d} ^{1-9,10}

super + {_,shift + }{u,i}
    bspc {desktop -f,window -d} {prev,next}

# Change focus with mouse
~button1
    bspc pointer -g focus

# Move, resize with mouse
super + button{1-3}
    bspc pointer -g {move,resize_side,resize_corner}

# ?????
super + !button{1-3}
    bspc pointer -t %i %i

# ?????
super + @button{1-3}
    bspc pointer -u



#--------------------------------------
# Multimedia
#--------------------------------------

# Volume keys
XF86Audio{Raise,Lower}Volume
    pactl set-sink-volume 0 {+5%,-- -5%}

XF86AudioMute
    pactl set-sink-volume 0 0%

# Multimedia keys
XF86Audio{Play,Next,Prev}
    ncmpcpp {toggle,next,prev}



#--------------------------------------
# Applications
#--------------------------------------

# Terminal
super + Return
    $TERMINAL

# File manager
super + f
    $TERMRUN $FM

# Web browser
super + w
    $BROWSER

# Text editor
super + t
    $TERMRUN $EDITOR

# Music player
super + m
    $TERMRUN $MPLAYER

# Music visualizer
super + v
    $TERMRUN $MVIZ

# Clock
super + c
    $TERMRUN $CLOCK

# Application launcher
super + space
    j4-dmenu-desktop --term=urxvt --dmenu="dmenu -i -fn 'Inconsolata-10'"

# Screenshot
{_,alt +} @Print
    scrot {_,-s}

# Screen lock
super + @F2
    lock



#--------------------------------------
# Reload
#--------------------------------------

# Reload sxhkd configuration on the fly
super + Escape
    pkill -USR1 -x sxhkd
