#!/bin/bash

source ~/.palettes/bash-style/base16/monokai
source ~/.palettes/bash-style/base16/colors
source ~/.palettes/bash-style/base16/dark

BAR_BG=${BACKGROUND}
STAT_BG=${DARK_GRAY}
BAR_FG=${FOREGROUND}
WARNING=${RED}

FONT="Meslo LG S-10"
#FONT="-*-terminus-medium-*-*-*-32-*-*-*-*-*-*-*"

H=5
W=200
