#!/bin/bash

PANEL_FIFO=/tmp/panel-fifo
#PANEL_FONT_FAMILY="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1"
PANEL_FONT_FAMILY=$FONT_LEMONBAR

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &

panel_clock()
{
    date '+C%a %F %H:%M'
}

while true; do
    panel_clock > "$PANEL_FIFO" &
    sleep 1
done &

source ~/.config/bspwm/panel/panel_colors

cat "$PANEL_FIFO" | ~/.config/bspwm/panel/panel_bar | \
    lemonbar -f "$PANEL_FONT_FAMILY" -F "$COLOR_FOREGROUND" \
             -B "$COLOR_BACKGROUND" &

wait
