#!/bin/bash

# Example panel for LemonBoy's bar

. ~/.config/bspwm/panel/panel_colors

num_mon=$(bspc query -M | wc -l)

while read -r line; do
    case $line in
        S*)
            tray="  %{F$COLOR_ICON_FG}%{T2}${line#?}%{T1}%{F-} "
            ;;
        C*)
            time="  %{F$COLOR_ICON_FG}%{T2}${line:1:1}%{T1}%{F-} ${line:2} "
            ;;
        D*)
            date="  %{F$COLOR_ICON_FG}%{T2}${line:1:1}%{T1}%{F-} ${line:2} "
            ;;
        B*)
            #battery="%{F$COLOR_BATTERY_FG}%{T2} ${line#?} %{T1}%{F-}"
            battery="  %{F$COLOR_ICON_FG}%{T2}${line:1:1}%{T1}%{F-} ${line:2} "
            ;;
        V*)
            volume="  %{F$COLOR_ICON_FG}%{T2}${line:1:1}%{T1}%{F-} ${line:2} "
            ;;
        R*)
            bright="  %{F$COLOR_ICON_FG}%{T2}${line:1:1}%{T1}%{F-} ${line:2} "
            ;;
        Z*)
            ram="  %{F$COLOR_ICON_FG}%{T2}${line:1:1}%{T1}%{F-} ${line:2} "
            ;;
        P*)
            cpu="  %{F$COLOR_ICON_FG}%{T2}${line:1:1}%{T1}%{F-} ${line:2} "
            ;;
        K*)
            kernel="  %{F$COLOR_ICON_FG}%{T2}${line:1:1}%{T1}%{F-} ${line:2} "
            ;;
        N*)
            network="  %{F$COLOR_ICON_FG}%{T2}${line:1:1}%{T1}%{F-} ${line:2} "
            ;;
        A*)
            #music="  %{F$COLOR_ICON_FG}%{T2}${line:1:1}%{T1}%{F-} ${line:2} "
            music="  %{F$COLOR_ICON_FG}%{T4}${line:1:5}%{T1}%{F-} ${line:6} "
            ;;
        #T*)
        #    title="  %{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}%{T1}${line#?}%{T1}%{B-}%{F-}  "
        #    ;;
        W*)
            # bspwm internal state
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    M*)
                        # active monitor
                        if [ $num_mon -gt 1 ] ; then
                            wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
                        fi
                        ;;
                    m*)
                        # inactive monitor
                        if [ $num_mon -gt 1 ] ; then
                            wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
                        fi
                        ;;
                    O*)
                        # focused occupied desktop
                        wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u}  %{T3}${name}%{T1}  %{-u}%{B-}%{F-}"
                        ;;
                    F*)
                        # focused free desktop
                        wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}%{+u}  %{T3}${name}%{T1}  %{-u}%{B-}%{F-}"
                        ;;
                    U*)
                        # focused urgent desktop
                        wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u}  %{T3}${name}%{T1}  %{-u}%{B-}%{F-}"
                        ;;
                    o*)
                        # occupied desktop
                        wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG}  %{T3}${name}%{T1}  %{B-}%{F-}"
                        ;;
                    f*)
                        # free desktop
                        wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}  %{T3}${name}%{T1}  %{B-}%{F-}"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG}  %{T3}${name}%{T1}  %{B-}%{F-}"
                        ;;
                    L*)
                        # layout
                        #wm_infos="$wm_infos  %{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG} ${name} %{B-}%{F-}"
                        ;;
                esac
                shift
            done
            ;;
    esac
    #printf "%s\n" "%{l}${wm_infos}%{r}${music}${network}${kernel}${cpu}${ram}${bright}${volume}${battery}${date}${time}${tray}"
    printf "%s\n" "%{l}${wm_infos}%{c}${music}%{r}${network}${volume}${battery}${date}${time}${tray}"
done
