#!/bin/bash

# Load keybindings
sxhkd &

# Initialize workspaces
#bspc monitor -d     
bspc monitor -d           

# Set borders, gaps, splits
for desktop in $(bspc query -D); do
	bspc config -d $desktop border_width 1;
	#bspc config -d $desktop border_width 0;
	bspc config -d $desktop window_gap   20;
done
unset desktop

bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config split_ratio        0.50

bspc config focused_border_color "$LIGHT_GRAY"
bspc config active_border_color  "$BLACK"
bspc config normal_border_color  "$BLACK"
bspc config urgent_border_color  "$RED"

# Load a panel
~/.config/bspwm/panel/panel &

# Hide cursor
#unclutter &

# Composite windows
compton -b
