#!/bin/sh

# Initialize workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# Set borders, gaps, splits
for desktop in $(bspc query -D); do
	#bspc config -d $desktop border_width 10;
	bspc config -d $desktop border_width 0;
	bspc config -d $desktop window_gap   20;
done
unset desktop

bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config split_ratio        0.50

bspc config focused_border_color "$COLOR15"
bspc config active_border_color  "$COLOR7"
bspc config normal_border_color  "$COLOR18"
bspc config urgent_border_color  "$COLOR1"

# Load a panel
#panel dzen2 &
#/home/mike/.config/bspwm/panel/panel &

# Load keybindings
sxhkd &

# Hide cursor
#unclutter &

# Composite windows
compton -b
