#!/bin/sh



#--------------------------------------
# Workspaces
#--------------------------------------

# Initialize
bspc monitor -d I II III IV V VI VII VIII IX X



#--------------------------------------
# Aesthetics
#--------------------------------------

# Borders and gaps
bspc config border_width        2
bspc config window_gap          12
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# Split behavior
bspc config split_ratio         0.50



#--------------------------------------
# X.org
#--------------------------------------

# Remove annoying beep
xset b off

# Don't turn off backlight for any reason
xset s off
xset -dpms
xset s noblank

# Set cursor theme
xsetroot -cursor_name left_ptr



#--------------------------------------
# Themes
#--------------------------------------

# Wallpaper
feh --bg-fill ~/Pictures/Wallpapers/QwVL3ze\ -\ Imgur.jpg



#--------------------------------------
# Applications
#--------------------------------------

# Daemons
mpd &
dropboxd &
CopyAgent &



#--------------------------------------
# Panel
#--------------------------------------

# panel dzen2 &



#--------------------------------------
# Rules
#--------------------------------------

#bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
